### PR TITLE
Added template tag.

### PR DESCRIPTION
**Pull request by jrutila**
Added template tag that can be used to get setting values in templates.

For example {% settings "mysetting" %}

### CODE REVIEW

**Comment by jrutila** [comment]
Hi, any news on this. I think the Travis build failed when it tried to install Django 1.3. Is there a way to restart the build to get this to green?

**Comment by jqb** [comment]
I've restarted build. There are still some flake8 issues:
https://travis-ci.org/jqb/django-settings/jobs/26817461

**Comment by jrutila** [comment]
Yay! All green.

**Comment by jqb** [comment]
Ok, thank you :)

**Pull request merged**
